    const PRODUCTS = [
      {
        id: 1,
        name: "The Bengal Blue: Square Tiger Glasses",
        category: "Glassware",
        price: 2999,
        originalPrice: 4999,
        badge: "Bestseller",
        emoji: "🐯",
        images: [
          "/Tiger/1.jpg",
          "/Tiger/2.jpg",
          "/Tiger/3.jpg",
          "/Tiger/4.jpg",
        ],
        story:
          "Born from a dawn spent watching a Bengal tiger at Ranthambore — the stillness before dawn broke, the tension in the air. This glassware is that breath held in time.",
        tag: "Cocktail Glasses, Tiger Glasses, Wildlife Barware",
        material: "Glass",
        dimensions: "350 ml",
      },
      {
        id: 2,
        name: "The Derby Dining: Ceramic  Bowls",
        category: "Bowls",
        price: 1999,
        originalPrice: 2499,
        badge: "Bestseller",
        emoji: "🌿",
        images: ["/Bowl/1.jpg", "/Bowl/2.jpg", "/Bowl/3.jpg", "/Bowl/4.jpg"],
        story:
          "Crafted for those who appreciate the fine balance of classic sport and contemporary art, this ceramic single-handle bowl features a beautifully detailed, wrap-around illustration of a thrilling horse race.",
        tag: "ceramic bowl, equestrian themed,wildlife tableware",
        material: "Ceramic",
        dimensions: "W x H: 20 x 5 cm · Capacity: 600 ml",
      },
      {
        id: 3,
        name: "The Regal Crest: Whiskey Decanter",
        category: "Drinkware",
        price: 2499,
        originalPrice: 3999,
        badge: null,
        emoji: "🏜️",
        images: ["/Decanter/1.jpg", "/Decanter/2.jpg", "/Decanter/3.jpg", "/Decanter/4.jpg", "/Decanter/5.jpg"],
        story:
          "Elevate your home bar to a realm of timeless luxury. Inspired by regal heritage and classic opulence, this exquisite crystal decanter is designed for those who celebrate life's finest moments.",
        tag: "Whiskey Decanter, Vintage Glassware, Barware Gift",
        material: "Borosilicate Glass",
        dimensions: "Capacity: 750 ml",
      },
      {
        id: 4,
        name: "The Taurus Blossom Hip Flask Set",
        category: "Drinkware",
        price: 2499,
        originalPrice: 3499,
        badge: "New",
        emoji: "🏺",
        images: ["/Flask/1.jpg", "/Flask/2.jpg", "/Flask/3.jpg", "/Flask/4.jpg", "/Flask/5.jpg", "/Flask/6.jpg", "/Flask/7.jpg"],
        story:
          "Crafted for the bold yet refined wanderer. This rugged leather-wrapped flask features a powerful bull framed by delicate, blooming flora a striking reminder that true strength always carries a touch of grace.",
        tag: "Flask, Leather, Barware, Gift",
        material: "Stainless Steel with Leather Wrapped, Brushed finish",
        dimensions: "W x H: 9 x 13.4 cm · Capacity: 240 ml",
      },
      {
        id: 5,
        name: "Striped Ceramic Decor Plate",
        category: "Decor Plates",
        price: 2499,
        originalPrice: 3999,
        badge: "New",
        emoji: "🌻",
        images: [
          "/Zebra-Decor-Plate/1.jpg",
          "/Zebra-Decor-Plate/2.jpg",
          "/Zebra-Decor-Plate/3.jpg",
          "/Zebra-Decor-Plate/4.jpg",
          "/Zebra-Decor-Plate/5.jpg"
        ],
        story:
          "Capture the untamed rhythm of the savanna. This bold, monochrome display piece blends striking geometric zebra stripes with fine wildlife art, bringing a sophisticated, exotic pulse into your modern home.",
        tag: "Decor Plate, Ceramic, Wildlife,Gift",
        material: "Ceramic",
        dimensions: "Height: 10 inches",
      },
      {
        id: 6,
        name: "Noble Horse: Whiskey Decanter",
        category: "Drinkware",
        price: 4999,
        originalPrice: 5999,
        badge: "Bestseller",
        emoji: "🎨",
        images: [
          "/Noble-Horse-Decanter/1.jpg",
          "/Noble-Horse-Decanter/2.jpg",
          "/Noble-Horse-Decanter/3.jpg",
          "/Noble-Horse-Decanter/4.jpg"
        ],
        story:
          "Capturing the essence of power, freedom, and untamed beauty, this stallion decanter turns your home bar into a gallery of high-end design. Crafted for those who demand their spirits be served with a side of dramatic flair.",
        tag: "Whiskey Decanter, Barware Gift",
        material: "Borosilicate Glass",
        dimensions: "Capacity: 1000 ml",
      },
      {
        id: 7,
        name: "The Whale & The Wit Glass Bottles (Set of 4)  ",
        category: "Glassware",
        price: 2499,
        originalPrice: 3999,
        badge: "New",
        emoji: "🎨",
        images: [
          "/WaterBottles/1.jpg",
          "/WaterBottles/2.jpg",
          "/WaterBottles/3.jpg",
          "/WaterBottles/4.jpg",
          "/WaterBottles/5.jpg",
        ],
        story:
          "Dive into hydration with a splash of personality. These sleek, reusable glass bottles pair majestic blue whale artwork with witty quotes, making daily wellness feel like a refreshing ocean breeze.",
        tag: "Eco-friendly, Reusable, Glass Bottle",
        material: "Borosilicate Glass",
        dimensions: "Capacity: 1000 ml",
      },
      {
        id: 8,
        name: " The Safari Siesta Collection (Set of 1) ",
        category: "Sippers",
        price: 999,
        originalPrice: 1499,
        badge: "Bestseller",
        emoji: "🎨",
        images: [
          "/Sippr/1.jpg",
          "/Sippr/2.jpg",
          "/Sippr/3.jpg",
          "/Sippr/4.jpg",
        ],
        story:
          "Unleash your untamed side with every sip. Featuring a cozy sleeping leopard and a curious hunter paired with cheeky text, these stylish glass tumblers elevate your daily hydration routine",
        tag: "Aesthetic, Reusable, Glass Sipper",
        material: "Toughened Glass",
        dimensions: "Weight: 180 grams · Capacity: 400 ml",
      },
      {
        id: 9,
        name: "Brahma Ceramic Decor Plate",
        category: "Decor Plates",
        price: 2499,
        originalPrice: 3999,
        badge: null,
        emoji: "✨",
        images: [
          "/Brahma-Decor-Plate/Brahma-Decor-Plate/1.jpg",
          "/Brahma-Decor-Plate/Brahma-Decor-Plate/2.jpg",
          "/Brahma-Decor-Plate/Brahma-Decor-Plate/3.jpg",
          "/Brahma-Decor-Plate/Brahma-Decor-Plate/4.jpg",
        ],
        story:
          "Evoke the grandeur of a vintage estate. This striking decor plate marries a classical, majestic stag portrait with a bold Art Deco border, bringing timeless wildlife elegance to your walls.",
        tag: "Ceramic, Deer, Decor, Plate, Gift",
        material: "Ceramic",
        dimensions: "Height: 10 inches",
      },
      {
        id: 10,
        name: "Clear Leopard Safari Mug ",
        category: "Cups",
        price: 1499,
        originalPrice: 1999,
        badge: "New",
        emoji: "☕",
        images: [
          "/Cup1/1.jpg",
          "/Cup1/2.jpg",
          "/Cup1/3.jpg",
          "/Cup1/4.jpg",
          "/Cup1/5.jpg",
        ],
        story:
          "Sip your morning brew in a tropical paradise. This crystal-clear glass mug showcases a graceful leopard prowling past ancient royal architecture, surrounded by lush palms and vibrant purple blooms.",
        tag: "Leopard, Mug, Transparent, Aesthetic",
        material: "Polypropylene, Wooden Handle",
        dimensions: "W x H: 5 x 5 cm · Capacity: 400 ml",
      },
      {
        id: 11,
        name: "The Woodland Fox Thermal Carafe",
        category: "Carafes",
        price: 3199,
        originalPrice: 3999,
        badge: "Bestseller",
        emoji: "🦓",
        images: [
          "/Jug1/1.jpg",
          "/Jug1/2.jpg",
          "/Jug1/3.jpg",
          "/Jug1/4.jpg",
          "/Jug1/5.jpg",
          "/Jug1/6.jpg",
        ],
        story:
          "Pour a touch of folklore into your morning ritual. This elegant ceramic-style carafe features a clever red fox nestled in whimsical woodland blooms, keeping your favorite brews beautifully warm.",
        tag: "Woodland, Fox, Thermal, Teapot",
        material: "Polypropylene, Wooden Handle",
        dimensions: "Weight: 400grams, Capacity: 1000 ml",
      },
      {
        id: 12,
        name: "Fishy Beverage Glass Carafe",
        category: "Carafes",
        price: 2499,
        originalPrice: 3999,
        badge: null,
        emoji: "🏺",
        images: [
          "/Jug2/1.jpg",
          "/Jug2/2.jpg",
          "/Jug2/3.jpg",
          "/Jug2/4.jpg",
          "/Jug2/5.jpg",
        ],
        story:
          "Brighten your breakfast table with a splash of coastal charm. This elegant glass carafe features a playful school of retro-styled fish, bringing a breezy, sun-drenched holiday feel to every pour.",
        tag: "Kitchenware, Wooden, Fish, Carafe",
        material: "Toughened Glass",
        dimensions: "Capacity: 1000 ml",
      },
      {
        id: 13,
        name: "The Red Panda Glass Canisters (Set of 2)",
        category: "Jars",
        price: 2199,
        originalPrice: 3999,
        badge: "New",
        emoji: "🏺",
        images: [
          "/Jar1/1.jpg",
          "/Jar1/2.jpg",
          "/Jar1/3.jpg",
          "/Jar1/4.jpg",
          "/Jar1/5.jpg",
          "/Jar1/6.jpg",
        ],
        story:
          "Keep your treats guarded by the cutest thieves in the forest. These charming glass canisters feature playful red pandas demanding snacks, adding a witty, wildlife-inspired touch to your kitchen counters.",
        tag: "Kitchen, Organiser, Wildlife, Jars",
        material: "Glass, Wooden Lid",
        dimensions: "L x W x H: 10 x 10 x 16 cm · Capacity: 1000 ml",
      },
      {
        id: 14,
        name: "The Round Bird Decorative Tray (Set of 2)",
        category: "Trays",
        price: 599,
        originalPrice: 999,
        badge: null,
        emoji: "📥",
        images: [
          "/Tray1/1.jpg",
          "/Tray1/2.jpg",
          "/Tray1/3.jpg",
          "/Tray1/4.jpg",
          "/Tray1/5.jpg",
        ],
        story:
          "Bring the serene beauty of a springtime garden indoors. This nesting tray set pairs a delicate songbird and vintage florals with a soothing mint backdrop, perfect for elegant home styling.",
        tag: "MDF Tray, Gift, Floral, Birds",
        material: "MDF",
        dimensions: "Height: 10 inches",
      },
      {
        id: 15,
        name: "Vanya Ceramic Decor Plate",
        category: "Decor Plates",
        price: 2499,
        originalPrice: 3999,
        badge: "Bestseller",
        emoji: "🌸",
        images: [
          "/Vanya-Decor-Plate/1.jpg",
          "/Vanya-Decor-Plate/2.jpg",
          "/Vanya-Decor-Plate/3.jpg",
          "/Vanya-Decor-Plate/4.jpg",
        ],
        story:
          "Immerse your space in dramatic elegance. This exquisite display plate captures a majestic tiger wading through midnight water, beautifully framed by a rich crimson border and luxurious gold trim.",
        tag: "Ceramic, Exotic, Tiger, Plate, Gift",
        material: "Ceramic",
        dimensions: "Height: 10 inches",
      },
      {
        id: 16,
        name: "Wooden Barasingha Grove Box",
        category: "Dining",
        price: 3499,
        originalPrice: 5999,
        badge: "New",
        emoji: "🦌",
        images: [
          "/Rotibox/1.jpg",
          "/Rotibox/2.jpg",
          "/Rotibox/3.jpg",
          "/Rotibox/4.jpg",
          "/Rotibox/5.jpg",
        ],
        story:
          "Handcrafted from rich, warm wood, this piece captures the magic of the deep forest. As majestic deer leap beneath golden palms, it brings the timeless spirit of wildlife into your home.",
        tag: "Wooden, decorative, storage, box",
        material: "Mango Wood",
        dimensions: "L x W x H: 22.3 x 22.3 x 10.9 cm · Capacity: 1600 ml",
      },
      {
        id: 17,
        name: "The Sweet Nectar Cookie Jar (Set of 2)",
        category: "Jars",
        price: 1999,
        originalPrice: 5999,
        badge: "New",
        emoji: "☕",
        images: ["/jar2/1.jpg", "/jar2/2.jpg", "/jar2/3.jpg", "/jar2/4.jpg"],
        story:
          "Bring the gentle hum of nature into your kitchen. Adorned with playful, hand-illustrated honeybees and delicate daisies, these charming glass jars add a touch of golden warmth to your countertop.",
        tag: "Bee, Glass, Kitchenware, Container",
        material: "Glass, Wooden Lid",
        dimensions: "Capacity: 650 ml",
      },
      {
        id: 18,
        name: "The Wild Cheetah Ceramic Mug (Set of 2)",
        category: "Cups",
        price: 2199,
        originalPrice: 3499,
        badge: null,
        emoji: "🐆",
        images: [
          "/Cup 2/1.jpg",
          "/Cup 2/2.jpg",
          "/Cup 2/3.jpg",
          "/Cup 2/4.jpg",
          "/Cup 2/5.jpg",
        ],
        story:
          "Awaken your wild side with every morning brew. Featuring a striking, hand-illustrated cheetah amidst warm, earthy tones, this mug brings the untamed beauty of the savannah right to your coffee routine.",
        tag: "Cheetah, Wildlife, Ceramic, Cups",
        material: "Ceramic",
        dimensions: "Capacity: 320 ml",
      },
      {
        id: 19,
        name: "The Chukker Classic Platter",
        category: "Platters",
        price: 3299,
        originalPrice: 4999,
        badge: "Limited Edition",
        emoji: "🍽️",
        images: [
          "/Platter1/1.jpg",
          "/Platter1/2.jpg",
          "/Platter1/3.jpg",
          "/Platter1/4.jpg",
          "/Platter1/5.jpg",
        ],
        story:
          "Galloping through a sun-drenched afternoon, this piece captures the timeless elegance and roaring energy of a classic polo match. A striking blend of athletic tradition and contemporary, sophisticated design.",
        tag: "Stripped, Polo, Horse, Platter",
        material: "Marble",
        dimensions: "L x W x H: 37 x 37 x 05 cm ",
      },
      {
        id: 20,
        name: "The BlackBuck Chiller Tub",
        category: "Drinkware",
        price: 1499,
        originalPrice: 2999,
        badge: null,
        emoji: "🦌",
        images: [
          "/Chiller/1.jpg",
          "/Chiller/2.jpg",
          "/Chiller/3.jpg",
          "/Chiller/4.jpg",
          "/Chiller/5.jpg",
          "/Chiller/6.jpg",
        ],
        story:
          "Elevate your celebrations with a touch of wilderness elegance. Adorned with a symmetrical, botanical gazelle illustration, this polished bucket keeps your spirits perfectly chilled from twilight till dawn.",
        tag: "Chiller, Bucket, Gazella, Barware",
        material: "Stainless Steel",
        dimensions: "L x W x H: 20 x 20 x 25 cm · Capacity: 4500 ml",
      },
      {
        id: 21,
        name: "The Royal Tiger Wine Glass (Set of 2)",
        category: "Glassware",
        price: 2199,
        originalPrice: 3999,
        badge: "Bestseller",
        emoji: "🐯",
        images: [
          "/wineglass/1.jpg",
          "/wineglass/2.jpg",
          "/wineglass/3.jpg",
          "/wineglass/4.jpg",
          "/wineglass/5.jpg",
          "/wineglass/6.jpg",
        ],
        story:
          "Bathed in the warm glow of dusk, this hand-etched glass brings the spirit of the Indian wilderness to your table. A majestic tiger watches over your evening, turning every sip into a storied ritual.",
        tag: "Luxury, Barware, Tiger, Glassware ",
        material: "Glass",
        dimensions: "Capacity: 450 ml",
      },
      {
        id: 22,
        name: "The Wildwood Scented Collection (Set of 4)",
        category: "Candles",
        price: 2599,
        originalPrice: 3499,
        badge: "Limited Edition",
        emoji: "🕯️",
        images: [
          "/Candle1/1.jpg",
          "/Candle1/2.jpg",
          "/Candle1/3.jpg",
          "/Candle1/4.jpg",
          "/Candle1/5.jpg",
        ],
        story:
          "Ignite your senses with hand-poured soy candles featuring exquisite wildlife art. From deep oudh to crisp basil, each jar releases a sensory journey into the heart of the untamed wilderness.",
        tag: "Aromatherapy, Handpoured, Soy, Candles",
        material: "Glass, Organic Soya Wax",
        dimensions: "35-40 Hours (each candle)",
      },
      {
        id: 23,
        name: "The Grey Heron Lamp (Including Bulb)",
        category: "Lamps",
        price: 1299,
        originalPrice: 2499,
        badge: null,
        emoji: "🕯️",
        images: [
          "/Lamp/1.jpg",
          "/Lamp/2.jpg",
          "/Lamp/3.jpg",
          "/Lamp/4.jpg"
        ],
        story:
          "Illuminate your space with the serene beauty of the wetlands. This handcrafted wooden lamp features a vibrant botanical shade alive with elegant herons, bringing a touch of nature indoors.",
        tag: "Lamp, Tabletop, Heron, Wildlife",
        material: "Fabric Shade, Wooden Base",
        dimensions: "H: 36 cm",
      },
      {
        id: 24,
        name: "Koi Fish Oatmeal Jars (Set of 2)",
        category: "Jars",
        price: 1999,
        originalPrice: 2499,
        badge: "New",
        emoji: "🐂",
        images: [
          "/Jar3/1.jpg",
          "/Jar3/2.jpg",
          "/Jar3/3.jpg",
          "/Jar3/4.jpg",
          "/Jar3/5.jpg",
          "/Jar3/6.jpg",
          "/Jar3/7.jpg"
        ],
        story:
          "Brighten your mornings with this playful, wildlife-inspired breakfast jar. Featuring a vibrant school of swimming koi fish, it turns your healthy meal prep into a beautiful, daily ritual.",
        tag: "Koi, Jar, Meal prep, Eco friendly",
        material: "Glass",
        dimensions: "Capacity: 800 ml",
      },
      {
        id: 25,
        name: "The Leopard Ice Bucket and Glass",
        category: "Drinkware",
        price: 2099,
        originalPrice: 2999,
        badge: null,
        emoji: "🕯️",
        images: ["/Chiller2/1.jpg", "/Chiller2/2.jpg", "/Chiller2/3.jpg"],
        story:
          "Elevate your hosting with the untamed elegance of the savannah. This stunning glass ice bucket and matching tumbler set features beautifully detailed leopards, bringing wild luxury to every chilled pour.",
        tag: "Barware, Leopard, Ice Bucket",
        material: "Glass",
        dimensions: "Capacity: 800 ml",
      },
      {
        id: 26,
        name: "The Safari Blossom 3-Tier Platter",
        category: "Platters",
        price: 4499,
        originalPrice: 5999,
        badge: "Most Viewed",
        emoji: "🐅",
        images: [
          "/Platter2/1.jpg",
          "/Platter2/2.jpg",
          "/Platter2/3.jpg",
          "/Platter2/4.jpg",
        ],
        story:
          "Elevate your high tea with a touch of the wild. This elegant, three-tiered ceramic stand pairs graceful cheetahs with soft pink florals, creating a majestic centerpiece for your table.",
        tag: "Serveware, Platter, Wildlife, Stand",
        material: "Metal",
        dimensions: "L x W x H: 29 x 29 x 44 cm · Weight: 1600 grams",
      },
      {
        id: 27,
        name: "The Enchanted Woodland Bowl",
        category: "Bowls",
        price: 1699,
        originalPrice: 2499,
        badge: null,
        emoji: "🌿",
        images: [
          "/Bowl2/1.jpg",
          "/Bowl2/2.jpg",
          "/Bowl2/3.jpg",
          "/Bowl2/4.jpg",
          "/Bowl2/5.jpg",
          "/Bowl2/6.jpg",
        ],
        story:
          "Savor calm mornings with this elegant glass breakfast bowl. Adorned with graceful, bounding deer and delicate golden flora, it brings a fairytale touch of the forest straight to your table.",
        tag: "Tea, Wildlife, Glassware, Hand-Etched",
        material: "Fine Glass",
        dimensions: "Capacity: 240 ml",
      },
      {
        id: 28,
        name: "The Jet-Set Duck Glass Purse Mug",
        category: "Glassware",
        price: 2799,
        originalPrice: 3499,
        badge: "Most Viewed",
        emoji: "🐯",
        images: [
          "/Glass1/1.jpg",
          "/Glass1/2.jpg",
          "/Glass1/3.jpg",
          "/Glass1/4.jpg"
        ],
        story:
          "Sip in style with this whimsical glass purse mug. Featuring a chic, cocktail-loving duck ready for the beach, it adds a playful, sunny vibe to your favorite iced beverages.",
        tag: "Purse, Glassware, Cocktail, Style",
        material: "Glass, Glass Straw",
        dimensions: "Capacity: 450 ml",
      },
      {
        id: 29,
        name: "Gaze of Wild Decor Plate",
        category: "Decor Plates",
        price: 2499,
        originalPrice: 3999,
        badge: null,
        emoji: "🐯",
        images: [
          "/Decorplate 1/1.jpg",
          "/Decorplate 1/2.jpg",
          "/Decorplate 1/3.jpg",
          "/Decorplate 1/4.jpg",
        ],
        story:
          "Bring the striking gaze of the wild onto your walls. This ornate ceramic art plate features a majestic leopard portrait framed by delicate pink vine illustrations and luxurious gold trim.",
        tag: "Ceramic, Exotic, Leopard, Plate, Gift",
        material: "Ceramic",
        dimensions: "Diameter: 10 inches",
      },
      {
        id: 30,
        name: "The Equine White Edition  (Set of 6)",
        category: "Coasters",
        price: 1699,
        originalPrice: 1999,
        badge: "Most Viewed",
        emoji: "🫖",
        images: [
          "/Coaster1/1.jpg",
          "/Coaster1/2.jpg",
          "/Coaster1/3.jpg",
          "/Coaster1/4.jpg",
          "/Coaster1/5.jpg",
        ],
        story:
          "Capture the raw strength and timeless elegance of the equine spirit. Featuring a striking, proud white horse framed by ornate vintage borders, these coasters bring noble artistry to your tabletop.",
        tag: "Equestrian, Vintage, Coasters, Tabletop",
        material: "Acrylic",
        dimensions: "L x H: 10 x 10 inches · Thickness: 5 mm",
      },
      {
        id: 31,
        name: "The Golden Pheasant Ceramic Valet Tray",
        category: "Trays",
        price: 1699,
        originalPrice: 2499,
        badge: null,
        emoji: "🫖",
        images: [
          "/Tray3/1.jpg",
          "/Tray3/2.jpg",
          "/Tray3/3.jpg",
          "/Tray3/4.jpg",
          "/Tray3/5.jpg",
          "/Tray3/6.jpg",
        ],
        story:
          "Organize your everyday essentials with vintage charm. This speckled ceramic catchall features a beautifully detailed golden pheasant, bringing a classic, nature-inspired touch to your entryway or nightstand.",
        tag: "Decor, Ceramic, Tray, Kitchenware",
        material: "Ceramic",
        dimensions: "L x W x TH: 20.3 x 10.2 x 1 cm · Weight: 700 grams",
      },
      {
        id: 32,
        name: "The Velvet Leopard Highball Glass (Set of 6)",
        category: "Glassware",
        price: 3499,
        originalPrice: 4999,
        badge: "Limited Edition",
        emoji: "🫖",
        images: [
          "/Glass 2/1.jpg",
          "/Glass 2/2.jpg",
          "/Glass 2/3.jpg",
          "/Glass 2/4.jpg",
        ],
        story:
          "Steeped in mystery and moody purple hues, this highball glass features a regal, sitting leopard framed by intricate baroque borders. Perfect for turning midnight cocktails into a cinematic experience.",
        tag: "Aesthetic, Highball, Cocktail, Glassware",
        material: "Glass",
        dimensions: "Capacity: 290 ml",
      },
      {
        id: 33,
        name: "The Equine Blue Edition  (Set of 6)",
        category: "Coasters",
        price: 1699,
        originalPrice: 1999,
        badge: null,
        emoji: "🫖",
        images: [
          "/Coaster2/1.jpg",
          "/Coaster2/2.jpg",
          "/Coaster2/3.jpg",
          "/Coaster2/4.jpg",
        ],
        story:
          "Capture the raw strength and timeless elegance of the equine spirit. Featuring a striking, proud white horse framed by ornate vintage borders, these coasters bring noble artistry to your tabletop.",
        tag: "Equestrian, Vintage, Coasters, Tabletop",
        material: "Acrylic",
        dimensions: "L x H: 10 x 10 inches · Thickness: 5 mm",
      },
      {
        id: 34,
        name: "Zebra Amber Tumbler Glass (Set of 6)",
        category: "Glassware",
        price: 3199,
        originalPrice: 5999,
        badge: "Bestseller",
        emoji: "🫖",
        images: ["/Glass 3/1.jpg", "/Glass 3/2.jpg", "/Glass 3/3.jpg"],
        story: "Bring the striking contrast of the savanna to your refreshment routine. These amber-tinted glasses showcase playfully illustrated zebras, adding a bold, wildlife-inspired flair to every pour.",
        tag: "Amber, Zebra, Drinkware, Cocktails",
        material: "Tinted Glass",
        dimensions: "Capacity: 300 ml",
      },
      {
        id: 35,
        name: "The Apex Wilderness Tumbler",
        category: "Sippers",
        price: 2199,
        originalPrice: 3499,
        badge: "New",
        emoji: "🥤",
        images: [
          "/Tumbler/1.jpg",
          "/Tumbler/2.jpg",
          "/Tumbler/3.jpg",
          "/Tumbler/4.jpg",
          "/Tumbler/5.jpg",
          "/Tumbler/6.jpg"
        ],
        story: "Engineered for the modern explorer, these insulated tumblers bring the fierce beauty of the wild into your daily commute. Keep your drinks perfectly chilled while showcasing bold, untamed artistry.",
        tag: "Artistic, Wildlife, Insulated, Tumbler",
        material: "Stainless Steel",
        dimensions: "Capacity: 1200 ml"
      },
      {
        id: 36,
        name: "The Imperial Peacock Candle (Set of 2)",
        category: "Candles",
        price: 2699,
        originalPrice: 3199,
        badge: "Out of Stock",
        emoji: "🕯️",
        images: [
          "/Candle 02/1.jpg",
          "/Candle 02/2.jpg",
          "/Candle 02/3.jpg",
          "/Candle 02/4.jpg",
          "/Candle 02/5.jpg",
          "/Candle 02/6.jpg"
        ],
        story: "Ignite your senses with an elegant glow. Encased in a brilliant gold vessel adorned with intricate peacock plumes, this luxury candle transforms any space into a serene, hypnotic sanctuary.",
        tag: "Aromatherapy, Luxury, Peacock, Candles",
        material: "Metal",
        dimensions: "W x H: 6 x 5 cm"
      },
      {
        id: 37,
        name: "Leopard Accent Tray",
        category: "Trays",
        price: 1199,
        originalPrice: 2999,
        badge: null,
        emoji: "🍱",
        images: [
          "/Tray 4/1.jpg",
          "/Tray 4/2.jpg",
          "/Tray 4/3.jpg",
          "/Tray 4/4.jpg",
          "/Tray 4/5.jpg",
          "/Tray 4/6.jpg"
        ],
        story: "Elevate your home aesthetic with a bold touch of the wild. Featuring a striking animal-print base wrapped in a sleek black frame, this versatile tray anchors your favorite decor pieces beautifully.",
        tag: "Minimalistic, Leopard, Tray, Serving",
        material: "Acrylic",
        dimensions: "L x W x H: 30 x 30 x 3.8 cm"
      },
      {
        id: 38,
        name: "The Whimsical Wildlife Sipper Duo",
        category: "Sippers",
        price: 1199,
        originalPrice: 1999,
        badge: "Most Viewed",
        emoji: "🥤",
        images: [
          "/Sipper 3/1.jpg",
          "/Sipper 3/2.jpg",
          "/Sipper 3/3.jpg",
          "/Sipper 3/4.jpg",
          "/Sipper 3/5.jpg",
          "/Sipper 3/6.jpg"
        ],
        story: "Add a splash of playfulness to your summer sips. Featuring a witty woodpecker and a diving duck, these bamboo-lidded can glasses make iced drinks feel like a sunny backyard getaway.",
        tag: "Summer, Glassware, Sipper, Modern",
        material: "Wooden Lid, Glass",
        dimensions: "Capacity: 540 ml"
      },
      {
        id: 39,
        name: "Buck & Cherry Ripple Glass",
        category: "Glassware",
        price: 1699,
        originalPrice: 2499,
        badge: "Bestseller",
        emoji: "🥛",
        images: [
          "/Glass 4/1.jpg",
          "/Glass 4/2.jpg",
          "/Glass 4/3.jpg",
          "/Glass 4/4.jpg"
        ],
        story: "Indulge your sweet tooth with a touch of elegance. Featuring an elegant gazelle nestled among bright summer cherries, this unique rippled glass adds a playful, artistic charm to your favorite iced treats.",
        tag: "Aesthetic, Ripple, Cherry, Drinkware",
        material: "Glass",
        dimensions: "Capacity: 510 ml"
      },
      {
        id: 40,
        name: "The Regal Heritage Dinner Set (16 Pieces)",
        category: "Dining",
        price: 6299,
        originalPrice: 8999,
        badge: "Customisable",
        emoji: "🍽️",
        images: [
          "/Dinnerset 1/1.jpg",
          "/Dinnerset 1/2.jpg",
          "/Dinnerset 1/3.jpg",
          "/Dinnerset 1/4.jpg"
        ],
        story: "Crafted for modern royalty, this porcelain set breathes life into ancient legacy. Every gold-rimmed edge and majestic crest turns daily dining into a grand, timeless celebration of history and art.",
        tag: "Luxury, Dinner set, Heritage, Tableware",
        material: "Ceramic",
        dimensions: "Serves 4"
      },
      {
        id: 41,
        name: "The Morning Chorus Cup",
        category: "Cups",
        price: 1699,
        originalPrice: 2499,
        badge: null,
        emoji: "☕",
        images: [
          "/Cup 3/1.jpg",
          "/Cup 3/2.jpg",
          "/Cup 3/3.jpg"
        ],
        story: "Wrap your hands around warmth and let your morning take flight. This delicate glass cup features a vibrant, hand-illustrated sparrow, bringing the peaceful serenity of nature to your daily brew.",
        tag: "Cozy, morning, sparrow, transparent, cup",
        material: "Glass",
        dimensions: "W x H: 5 x 6 cm · Capacity: 150 ml"
      },
      {
        id: 42,
        name: "The Koi Pond Mosaic Coaster (Set of 6)",
        category: "Coasters",
        price: 1799,
        originalPrice: 1999,
        badge: "Most Viewed",
        emoji: "🪵",
        images: [
          "/Coaster 3/1.jpg",
          "/Coaster 3/2.jpg",
          "/Coaster 3/3.jpg",
          "/Coaster 3/4.jpg",
          "/Coaster 3/5.jpg"
        ],
        story: "Bring a splash of tranquil elegance to your tabletop. These rich wooden coasters feature a vibrant, mosaic-style digital art inlay of swirling koi fish, blending wildlife beauty with functional home decor.",
        tag: "Mosaic, Koi, Wooden, Barware",
        material: "Wooden",
        dimensions: "W x H: 8.9 x 8.9 cm"
      },
      {
        id: 43,
        name: "The Last Shot (Set of 4)",
        category: "Glassware",
        price: 1699,
        originalPrice: 2499,
        badge: "New",
        emoji: "🥃",
        images: [
          "/Glass 5/1.jpg",
          "/Glass 5/2.jpg",
          "/Glass 5/3.jpg",
          "/Glass 5/4.jpg",
          "/Glass 5/5.jpg"
        ],
        story: "Ignite the night with a wild, playful spirit. Featuring a charmingly exhausted tiger artwork, these vibrant shot glasses bring bold, humorous wildlife energy to your next unforgettable party setup.",
        tag: "Tequilla, Drinkware, Barware, Shot glasses",
        material: "Glass, Wooden Tray",
        dimensions: "Capacity: 100 ml"
      },
      {
        id: 44,
        name: "The Sunlit Cranes Decor Plate",
        category: "Decor Plates",
        price: 2499,
        originalPrice: 3999,
        badge: null,
        emoji: "🍽️",
        images: [
          "/Decor Plate 2/1.jpg",
          "/Decor Plate 2/2.jpg",
          "/Decor Plate 2/3.jpg",
          "/Decor Plate 2/4.jpg"
        ],
        story: "Capture the serene majesty of a golden dawn. This porcelain plate showcases graceful cranes soaring across a brilliant rising sun, bordered by elegant botanical details to elevate your dining table.",
        tag: "Ceramic, Sunrise, Crane, Plate, Gift",
        material: "Ceramic",
        dimensions: "Diameter: 10 inches"
      },
      {
        id: 45,
        name: "The Gilded Leopard Coaster (Set of 6)",
        category: "Coasters",
        price: 1699,
        originalPrice: 1999,
        badge: "Most Viewed",
        emoji: "🪵",
        images: [
          "/Coaster 4/1.jpg",
          "/Coaster 4/2.jpg",
          "/Coaster 4/3.jpg",
          "/Coaster 4/4.jpg",
          "/Coaster 4/5.jpg"
        ],
        story: "Bring fierce, untamed luxury to your desk or home bar. Featuring a striking gold-leaf leopard illustration, these premium coasters effortlessly shield your surfaces while radiating bold, timeless sophistication.",
        tag: "Gold, Barware, Leopard, Decor",
        material: "Acrylic",
        dimensions: "L x H: 10 x 10 inches · Thickness: 5 mm"
      },
      {
        id: 46,
        name: "The Prowling Tigers Rocking Glass (Set of 4)",
        category: "Glassware",
        price: 2799,
        originalPrice: 3999,
        badge: "Bestseller",
        emoji: "🥃",
        images: [
          "/Glass 6/1.jpg",
          "/Glass 6/2.jpg",
          "/Glass 6/3.jpg",
          "/Glass 6/4.jpg",
          "/Glass 6/5.jpg",
          "/Glass 6/6.jpg"
        ],
        story: "Elevate your home bar with a touch of the wild. These unique, rocking cocktail glasses feature an intricate digital illustration of circling tigers, adding dynamic wildlife energy to every sip.",
        tag: "Whiskey, Cocktail, Barware, Unique",
        material: "Glass",
        dimensions: "L x W x H: 6 x 6 x 11 cm"
      },
      {
        id: 47,
        name: "The Ocean Wave Platter with Shell Dipper",
        category: "Platters",
        price: 1699,
        originalPrice: 2199,
        badge: "New",
        emoji: "🍽️",
        images: [
          "/Platter 3/1.jpg",
          "/Platter 3/2.jpg",
          "/Platter 3/3.jpg",
          "/Platter 3/4.jpg",
          "/Platter 3/5.jpg"
        ],
        story: "Bring the serene beauty of the coastline to your table. This deep blue, wave-textured ceramic platter features a built-in scalloped shell dipping compartment, making every appetizer look like a seaside luxury.",
        tag: "Serveware, Appetizer, Shell, Platter",
        material: "Ceramic",
        dimensions: "W x TH: 28 x 25.5 x 0.5 cm · Weight: 1000 gr"
      },
      {
        id: 48,
        name: "Pichwai Brass Planter",
        category: "Planters",
        price: 1399,
        originalPrice: 2499,
        badge: null,
        emoji: "🪴",
        images: [
          "/Planter 1/1.jpg",
          "/Planter 1/2.jpg",
          "/Planter 1/3.jpg",
          "/Planter 1/4.jpg",
          "/Planter 1/5.jpg"
        ],
        story: "Invite tranquility and spiritual grace into your home. This elegant brass planter features a beautiful, traditional Pichwai-inspired illustration of a sacred cow cradled by blooming pink lotuses.",
        tag: "Pichwai, Brass, Planter, Tabletop",
        material: "Metal",
        dimensions: "W x H: 8 x 14 cm · Diameter: 14 cm"
      },
      {
        id: 49,
        name: "The Grizzly Grind Travel Mug",
        category: "Cups",
        price: 1699,
        originalPrice: 2499,
        badge: "Limited Edition",
        emoji: "🐻",
        images: [
          "/SteerMug/1.jpg",
          "/SteerMug/2.jpg",
          "/SteerMug/3.jpg",
          "/SteerMug/4.jpg",
          "/SteerMug/5.jpg",
          "/SteerMug/6.jpg"
        ],
        story: "Fuel your wild side. Built for early mornings and untamed days, this rugged travel mug keeps your brew steaming hot while reminding everyone not to mess with you before coffee.",
        tag: "Grizzly, Seld, Steel, Coffee mug, Aesthet",
        material: "Stainless Steel, Plastic",
        dimensions: "Capacity: 380 ml"
      },
      {
        id: 50,
        name: "The Golden Stag Candle Holder",
        category: "Candles",
        price: 1199,
        originalPrice: null,
        badge: "New",
        emoji: "🕯️",
        images: [
          "/Candle 3/1.jpg",
          "/Candle 3/2.jpg",
          "/Candle 3/3.jpg",
          "/Candle 3/4.jpg",
          "/Candle 3/5.jpg",
          "/Candle 3/6.jpg"
        ],
        story: "Bring the quiet majesty of the winter forest indoors. This intricately detailed, golden deer cradles your favorite taper candle, casting a warm, elegant glow over cozy evenings and sophisticated dinners.",
        tag: "Candlestick, Holder, Golden, Stag",
        material: "Aluminium",
        dimensions: "L x W x H: 11.5 x 5.5 x 13.5 cm"
      },
      {
        id: 51,
        name: "The Royal Peacock Palace Plate",
        category: "Decor Plates",
        price: 2999,
        originalPrice: 3999,
        badge: "Most Viewed",
        emoji: "🦚",
        images: [
          "/Decor Plate 4/1.jpg",
          "/Decor Plate 4/2.jpg",
          "/Decor Plate 4/3.jpg",
          "/Decor Plate 4/4.jpg",
          "/Decor Plate 4/5.jpg"
        ],
        story: "Capture the regal elegance of ancestral palaces. Featuring an exquisitely detailed peacock amidst striking arches, this vibrant ceramic art piece brings an air of majestic luxury to your home decor.",
        tag: "Ceramic, Royal, Peacock, Plate, Gift",
        material: "Ceramic",
        dimensions: "Diameter: 10 inches"
      },
      {
        id: 52,
        name: "Gaj Mukh Glass Casserole (Set of 2)",
        category: "Dining",
        price: 2499,
        originalPrice: 3499,
        badge: null,
        emoji: "🐘",
        images: [
          "/Bowl 3/1.jpg",
          "/Bowl 3/2.jpg",
          "/Bowl 3/3.jpg",
          "/Bowl 3/4.jpg",
          "/Bowl 3/5.jpg"
        ],
        story: "Elevate your dining experience with a touch of the wild. Crafted from clear glass and accented with elegant elephant motifs, these covered bowls beautifully showcase your culinary creations.",
        tag: "Elephant, Casserole, Kitchenware, Serv",
        material: "Glass",
        dimensions: "Capacity: 1000 ml (each)"
      },
      {
        id: 53,
        name: "The Cheese Thief Stackable Jars",
        category: "Jars",
        price: 2199,
        originalPrice: 3199,
        badge: null,
        emoji: "🐭",
        images: [
          "/Jar 4/1.jpg",
          "/Jar 4/2.jpg",
          "/Jar 4/3.jpg",
          "/Jar 4/4.jpg",
          "/Jar 4/5.jpg"
        ],
        story: "Add a dash of playful charm to your countertop. Featuring adorable little mice hunting for cheese, these stacked glass jars keep your favorite cookies, nuts, and treats fresh and visible.",
        tag: "Stackable, Container, Organizer, Kitchen",
        material: "Glass",
        dimensions: "L x W x H: 12.5 x 12.5 x 18 cm"
      },
      {
        id: 54,
        name: "The White Tiger Oil Dispenser",
        category: "Kitchenware",
        price: 1799,
        originalPrice: 2199,
        badge: null,
        emoji: "🐅",
        images: [
          "/Kitchen 1/1.jpg",
          "/Kitchen 1/2.jpg",
          "/Kitchen 1/3.jpg",
          "/Kitchen 1/4.jpg",
          "/Kitchen 1/5.jpg",
          "/Kitchen 1/6.jpg"
        ],
        story: "Infuse your kitchen with the untamed beauty of the jungle. This glossy, crimson ceramic oil dispenser features a serene white tiger admiring a blooming flower, elevating your daily culinary rituals.",
        tag: "Pourer, Tiger, Dispenser, Oil, Cruet",
        material: "Ceramic",
        dimensions: "Capacity: 500 ml"
      },
      {
        id: 55,
        name: "The Sassy Flamingo Stemless Glass (Set of 6)",
        category: "Cups",
        price: 3199,
        originalPrice: null,
        badge: "Bestseller",
        emoji: "🦩",
        images: [
          "/Glass 7/1.jpg",
          "/Glass 7/2.jpg",
          "/Glass 7/3.jpg",
          "/Glass 7/4.jpg"
        ],
        story: "Sip in style with ultimate main character energy. Featuring fabulously dressed flamingos and chic quotes, these smoky-tinted stemless glasses add a playful, glamorous pop to your next cocktail hour.",
        tag: "Cocktail, Drinkware, Barware, Party",
        material: "Tinted Glass",
        dimensions: "Capacity: 350 ml (each)"
      },
      {
        id: 56,
        name: "The Jaipur Gold Elephant Vase",
        category: "Planters",
        price: 1499,
        originalPrice: 2999,
        badge: "New",
        emoji: "🐘",
        images: [
          "/Planter 2/1.jpg",
          "/Planter 2/2.jpg",
          "/Planter 2/3.jpg",
          "/Planter 2/4.jpg"
        ],
        story: "Bring the grandeur of royal palaces into your home. This stunning golden vase showcases a beautifully caparisoned heritage elephant, making it the perfect majestic centerpiece for your favorite blooms.",
        tag: "Gold, Planter, Royal, Vase",
        material: "Tinted Glass",
        dimensions: "L x W x H: 10.5 x 10.5 x 15.5 cm"
      },
      {
        id: 57,
        name: "The Midnight Merlot Black Cat Goblet (Set of 2)",
        category: "Glassware",
        price: 1999,
        originalPrice: null,
        badge: "Most Viewed",
        emoji: "🐈‍⬛",
        images: [
          "/Glass 8/1.jpg",
          "/Glass 8/2.jpg",
          "/Glass 8/3.jpg",
          "/Glass 8/4.jpg",
          "/Glass 8/5.jpg"
        ],
        story: "Unwind with a touch of feline mystery. This elegant crystal wine glass features an adorable black cat nestled among lush grapevines, making your evening pour a delightfully magical experience.",
        tag: "Vineyard, Drinkware, Barware, Cat",
        material: "Glass",
        dimensions: "Capacity: 350 ml (each)"
      },
      {
        id: 58,
        name: "Cold Coffee Brew Scented Candle (Organic Soya)",
        category: "Candles",
        price: 999,
        originalPrice: 1999,
        badge: "Limited Edition",
        emoji: "☕",
        images: [
          "/Candle 4/1.jpg",
          "/Candle 4/2.jpg",
          "/Candle 4/3.jpg",
          "/Candle 4/4.jpg",
          "/Candle 4/5.jpg"
        ],
        story: "Wake up your senses with an exotic morning ritual. Featuring a majestic prowling tiger, this handpoured organic soy candle fills your room with the rich, bold aroma of fresh cold brew coffee.",
        tag: "Organic, Soya, Scented, Gifting, Coffee",
        material: "Glass",
        dimensions: "W x H: 8 x 9 cm · Capacity: 450 ml (each)"
      },
      {
        id: 59,
        name: "The Imperial Antler Glass Buffet Server",
        category: "Jars",
        price: 3499,
        originalPrice: 4999,
        badge: "Out of Stock",
        emoji: "🦌",
        images: [
          "/Jar 5/1.jpg",
          "/Jar 5/2.jpg",
          "/Jar 5/3.jpg",
          "/Jar 5/4.jpg"
        ],
        story: "Elevate your hosting with sophisticated forest charm. This exquisite three-tier stand features crystal-clear ribbed glass dishes crowned with elegant golden stag handles, perfect for serving nuts, candies, and exquisite holiday treats.",
        tag: "Stag, Glass, Tiered, Server, Stand",
        material: "Glass, Metal Stand",
        dimensions: "Capacity: 1500 ml"
      },
      {
        id: 60,
        name: "The Aviator Elephant's Pickle Jar",
        category: "Jars",
        price: 1799,
        originalPrice: 1999,
        badge: null,
        emoji: "🐘",
        images: [
          "/Jar 6/1.jpg",
          "/Jar 6/2.jpg",
          "/Jar 6/3.jpg",
          "/Jar 6/4.jpg",
          "/Jar 6/5.jpg",
          "/Jar 6/6.jpg"
        ],
        story: "Follow the daring captain on his quest for the perfect spice. From the heart of a rain-kissed monsoon harvest, discovery takes flight. See his exotic cargo and join the journey.",
        tag: "Elephant, Art, Wildlife, Decor, Pickle",
        material: "Glass",
        dimensions: "Capacity: 1500 ml"
      },
      {
        id: 61,
        name: "Parakeet: Echoes of the Jharokha (Set of 2)",
        category: "Candles",
        price: 1799,
        originalPrice: 2199,
        badge: "Most Viewed",
        emoji: "🦜",
        images: [
          "/candle 5/1.jpg",
          "/candle 5/2.jpg",
          "/candle 5/3.jpg",
          "/candle 5/4.jpg",
          "/candle 5/5.jpg",
          "/candle 5/6.jpg"
        ],
        story: "A royal secret whispers from the stone. Drawn to the flickering warmth of a forgotten palace, one emerald wanderer returns. Discover what the emperor left behind.",
        tag: "Parrot, Heritage, Premium, Candle Stand",
        material: "Glass",
        dimensions: "L x W x H: 8.5 x 8 x 14 cm · Diameter: 3 inches"
      },
      {
        id: 62,
        name: "Midnight Stallions: Guardians of Books",
        category: "Tabletop",
        price: 2999,
        originalPrice: 4499,
        badge: "Limited Edition",
        emoji: "🐴",
        images: [
          "/Bookstand/1.jpg",
          "/Bookstand/2.jpg",
          "/Bookstand/3.jpg",
          "/Bookstand/4.jpg",
          "/Bookstand/5.jpg"
        ],
        story: "Inspired by wild stallions charging through midnight valleys, these sculpted pieces capture untamed freedom and timeless grace, bringing the raw, majestic spirit of the open wilderness directly into your home.",
        tag: "Wildlife, Home decor, Bookends, Horse",
        material: "Resin",
        dimensions: "D x W x H: 21 x 3 x 30 cm"
      },
      {
        id: 63,
        name: "Vegan Leather Golden Quill Cutlery Organiser",
        category: "Tabletop",
        price: 2499,
        originalPrice: 3199,
        badge: null,
        emoji: "🪶",
        images: [
          "/Spoonrack/1.jpg",
          "/Spoonrack/2.jpg",
          "/Spoonrack/3.jpg",
          "/Spoonrack/4.jpg",
          "/Spoonrack/5.jpg",
          "/Spoonrack/6.jpg"
        ],
        story: "Inspired by whimsical woodland feasts, this artisanal organizer celebrates the charming hedgehog. Infused with golden elegance, it transforms everyday dining into an enchanting celebration of untamed nature and luxury living.",
        tag: "Luxury, Dining, Wildlife, Organiser",
        material: "Leather",
        dimensions: "D x W x H: 16 x 13 x 18 cm"
      },
      {
        id: 64,
        name: "The Canopy Feast Artisanal Glass Basket",
        category: "Kitchenware",
        price: 1999,
        originalPrice: 2499,
        badge: "New",
        emoji: "🧺",
        images: [
          "/Basket/1.jpg",
          "/Basket/2.jpg",
          "/Basket/3.jpg",
          "/Basket/4.jpg"
        ],
        story: "Inspired by sunlit tropical orchards, this glass piece captures the lively spirit of wild parakeets feasting among sweet summer fruits, bringing a beautiful slice of untamed paradise into your home.",
        tag: "Luxury, Fruit basket, Decor, Tableware",
        material: "Glass, Wooden Handle",
        dimensions: "Capacity: 2200 ml"
      },
      {
        id: 65,
        name: "Blue Pottery Marble Pedestal Bowl",
        category: "Bowls",
        price: 4999,
        originalPrice: 5999,
        badge: null,
        emoji: "🐇",
        images: [
          "/Bowl 4/1.jpg",
          "/Bowl 4/2.jpg",
          "/Bowl 4/3.jpg",
          "/Bowl 4/4.jpg",
          "/Bowl 4/5.jpg"
        ],
        story: "This exquisite marble bowl captures wild hares leaping through a tapestry of blue flora, bringing the quiet elegance of nature's hidden sanctuaries to your home.",
        tag: "Rabbit, Marble, Pedestal, Blue Pottery",
        material: "Marble, Marble Pedestal",
        dimensions: "W x H: 22.5 x 15 cm"
      },
      {
        id: 66,
        name: "Monkey Sculpted Pendant Light",
        category: "Lamps",
        price: 1699,
        originalPrice: 2999,
        badge: "Most Viewed",
        emoji: "🐒",
        images: [
          "/Lamp 2/1.jpg",
          "/Lamp 2/2.jpg",
          "/Lamp 2/3.jpg",
          "/Lamp 2/4.jpg",
          "/Lamp 2/5.jpg"
        ],
        story: "The playful spirit of deep rainforest canopies, this hand-sculpted piece captures a curious monkey swinging through golden shadows, casting an enchanting, warm glow across your entire modern sanctuary.",
        tag: "Pendant, Wildlife, Monkey, Lighting",
        material: "Resin",
        dimensions: "L x W x H: 21.5 x 25 x 32 cm"
      },
      {
        id: 67,
        name: "Wire Egg Basket",
        category: "Kitchenware",
        price: 1199,
        originalPrice: 1499,
        badge: null,
        emoji: "🥚",
        images: [
          "/Eggbasket/1.jpg",
          "/Eggbasket/2.jpg",
          "/Eggbasket/3.jpg",
          "/Eggbasket/4.jpg",
          "/Eggbasket/5.jpg"
        ],
        story: "The minimalist wire sculpture captures a timeless rustic elegance, welcoming the gentle, nurturing spirit of nature directly into your culinary sanctuary.",
        tag: "Kitchen, Organiser, Decor, Aesthetic",
        material: "Metal",
        dimensions: "D x W x H: 26 x 21 x 34 cm"
      },
      {
        id: 68,
        name: "Save the Jungles Decor Plate",
        category: "Decor Plates",
        price: 2499,
        originalPrice: 3199,
        badge: null,
        emoji: "🌿",
        images: [
          "/Decor plate 5/1.jpg",
          "/Decor plate 5/2.jpg",
          "/Decor plate 5/3.jpg",
          "/Decor plate 5/4.jpg",
          "/Decor plate 5/5.jpg"
        ],
        story: "Deep within the ancient, untouched forest, a hidden sanctuary thrives. This exclusive piece captures the rhythmic dance of the wild canopy, bringing the raw, majestic pulse of nature indoors.",
        tag: "Ceramic, Forest, Decor, Save Forest",
        material: "Ceramic",
        dimensions: "Diameter: 10 inches"
      },
      {
        id: 69,
        name: "The Roaring Century Premium Collector's Glass",
        category: "Decor Plates",
        price: 2499,
        originalPrice: 2199,
        badge: null,
        emoji: "🦁",
        images: [
          "/Glass 9/1.jpg",
          "/Glass 9/2.jpg",
          "/Glass 9/3.jpg",
          "/Glass 9/4.jpg"
        ],
        story: "Uniting the fierce majesty of the savanna's true king with the spirited passion of the pitch. This masterfully crafted piece celebrates the ultimate roar of triumph, elegance, and sporting legacy.",
        tag: "Wildlife, Cricket, Glassware, Barware",
        material: "Glass",
        dimensions: "Capacity: 450 ml"
      },
      {
        id: 70,
        name: "The Imperial Stag Pourer",
        category: "Drinkware",
        price: 1199,
        originalPrice: 1999,
        badge: null,
        emoji: "🦌",
        images: [
          "/Drinkware 6/1.jpg",
          "/Drinkware 6/2.jpg",
          "/Drinkware 6/3.jpg",
          "/Drinkware 6/4.jpg",
          "/Drinkware 6/5.jpg"
        ],
        story: "Foraged from the depths of mist-veiled highlands, the majestic stag rules the wild. This finely sculpted heirloom captures his regal spirit, preserving your finest vintages with unmatched, timeless elegance.",
        tag: "Stag, Pourer, Wine, Barware, Gift",
        material: "Stainless Steel",
        dimensions: "D x W x H: 12.3 x 6 x 6 cm"
      },
      {
        id: 71,
        name: "The Peacock Luxury Dessert Coupe (Set of 2)",
        category: "Bowls",
        price: 999,
        originalPrice: 1499,
        badge: null,
        emoji: "🦚",
        images: [
          "/Bowl 5/1.jpg",
          "/Bowl 5/2.jpg",
          "/Bowl 5/3.jpg",
          "/Bowl 5/4.jpg",
          "/Bowl 5/5.jpg"
        ],
        story: "Inspired by the iridescent splendor of the royal peacock, this exquisite glassware mirrors the majestic feathers of the wild. Elevate ordinary moments into a grand, untamed epicurean ritual.",
        tag: "Peacock, Glassware, Decor, Tableware",
        material: "Borosilicate Glass",
        dimensions: "Capacity: 220 ml"
      },
      {
        id: 72,
        name: "Leopard Skin Butter Box",
        category: "Tabletop",
        price: 999,
        originalPrice: null,
        badge: "New",
        emoji: "🐆",
        images: [
          "/Butterbox/1.jpg",
          "/Butterbox/2.jpg",
          "/Butterbox/3.jpg"
        ],
        story: "Inspired by the elusive elegance of the leopard moving through golden grasslands, this exquisite porcelain piece transforms daily dining rituals into a wild, untamed celebration of pure majestic beauty.",
        tag: "Leopard, Wildlife, Butter, Box, Gift",
        material: "Stainless Steel",
        dimensions: "Capacity: 220 ml"
      },
      {
        id: 73,
        name: "The Lioness Pride Decor Plate",
        category: "Decor Plates",
        price: 2499,
        originalPrice: 3199,
        badge: "Most Viewed",
        emoji: "🦁",
        images: [
          "/Decor Plate 6/1.jpg",
          "/Decor Plate 6/2.jpg",
          "/Decor Plate 6/3.jpg",
          "/Decor Plate 6/4.jpg",
          "/Decor Plate 6/5.jpg"
        ],
        story: "Cradle the tender bond of the wild Gir. Set against royal botanicals, a lioness protects her cubs, capturing a timeless narrative of raw maternal power and majestic wildlife heritage.",
        tag: "Ceramic, Lioness, Decor, Gift",
        material: "Ceramic",
        dimensions: "Diameter: 10 inches"
      },
      {
        id: 74,
        name: "Antelope Multipurpose Bowl",
        category: "Tabletop",
        price: 2499,
        originalPrice: 3199,
        badge: null,
        emoji: "🦌",
        images: [
          "/Ashtray/1.jpg",
          "/Ashtray/2.jpg",
          "/Ashtray/3.jpg",
          "/Ashtray/4.jpg",
          "/Ashtray/5.jpg"
        ],
        story: "Embodying the gentle grace of a dappled fawn resting in a sunlit grove, this sculptural treasure organizes your finest jewels within a majestic, golden embrace of sophisticated wildlife poetry.",
        tag: "Ceramic, Antelope, Decor, Gift",
        material: "Ceramic",
        dimensions: "Diameter: 10 inches"
      }
      },
      {
        id: 75,
        name: "Equestrian Luxury Martini Glass Collection (Set of 2)",
        category: "Glassware",
        price: 1699,
        originalPrice: 2999,
        badge: "Most Viewed",
        emoji: "🍸",
        images: [
          "/wineglass/1.jpg",
          "/wineglass/2.jpg",
          "/wineglass/3.jpg",
          "/wineglass/4.jpg",
          "/wineglass/5.jpg",
          "/wineglass/6.jpg"
        ],
        story: "Elevate your home bar with these elegant martini glasses featuring a beautifully etched horse motif, set against a rich, moody backdrop perfect for sophisticated gatherings and digital wildlife art lovers.",
        tag: "Etched glasses, Horse, Cocktail, Barware",
        material: "Glass",
        dimensions: "Capacity: 135 ml"
      }
    ];
